### ISSUE TITLE
No support for route parameters

### ISSUE THREAD

**Issue by alexweltman** [DavidePastore/Slim-Validation#18]
Only validation of query parameters (such as **param** in ``` '/myEndPoint?param=foo'```) is supported.
We use route parameters in most of our routes. This same route would be defined like this:
```php 
$app->get('/myEndPoint/{param}'
```
and when an HTTP request is sent, the URI could look like this: ```'/myEndPoint/foo'```.

It would be great if we could validate both query params and route params.

**Comment by DavidePastore** [comment]
Hi @alexweltman , thanks for using this middleware. I integrated the route parameters validation and I'll publish another release with this feature.

**Comment by DavidePastore** [comment]
Published `0.4.0` release with this feature.
