### ISSUE TITLE
Setting a template for a rule with no effect

### ISSUE THREAD

**Issue by gus27** [DavidePastore/Slim-Validation#22]
Setting a template for a rule (to specify your own error message) currently has no effect on the error messages you get with `$errors = $request->getAttribute('errors');`

Example: I have two regex rules and I'd like to prevent the default error message "xxx must validate against regex".

```
$aValidator = v::regex('/^[a-zA-Z]([-.a-zA-Z0-9]{0,61}[a-zA-Z0-9]){0,1}$/')->setTemplate('Hostname {{name}} is not valid');
$bValidator = v::regex('/^[a-zA-Z]$/')->setTemplate('Entry {{name}} should contain only letters');
$validators = array(
  'a' => $aValidator,
  'b' => $bValidator
);
$app->put('/entity', function ($request, $response, $args) {
    if ($request->getAttribute('has_errors')) {
        $errors = $request->getAttribute('errors');

        // For an invalid entry of 'a' $errors contains here the 
        // default error message instead of the template message:
        // array(1) {  ["a"]=> array(1) { 
        //    [0]=> string(86) ""1abfx53357" must validate against "/^[a-zA-Z]([-.a-zA-Z0-9]{0,61}[a-zA-Z0-9]){0,1}$/"" 
        // } }
    }    
})->add(new DavidePastore\Slim\Validation\Validation($validators));
```

I have not seen any way to retrieve the error messages that are set by the `setTemplate` method. As far as I have tracked it down the issue could be in line 125 of *Validation.php*:

`                  $this->errors[implode('.', $actualKeys)] = $exception->getMessages();`
When you change this to 
`                    $this->errors[implode('.', $actualKeys)] = [$exception->getMainMessage()];`
the error messages contain the template text.

Did I overlook something? 
If not it would be nice if these messages could be activated/changed by a switch, e.g.:

```
    protected $use_templates = FALSE;
    ...
    $this->errors[implode('.', $actualKeys)] = ( $this->use_templates ? [$exception->getMainMessage()] : $exception->getMessages() );
```

**Comment by DavidePastore** [comment]
Hi @gus27 ! Thanks for your feedback. Could you please take a look to https://github.com/DavidePastore/Slim-Validation/issues/23? It should do what you want. What do you think of it (you can find the documentation [here](https://github.com/DavidePastore/Slim-Validation/tree/use-template#use-templates))?

**Comment by gus27** [comment]
Hi @DavidePastore - Just checked out the _use-template_ branch. It works like a charm. The new options parameter is a good idea to keep backwards compatibility.

**Comment by DavidePastore** [comment]
You can find this feature in the new 0.5.0 version.
