### ISSUE TITLE
Add support for optional parameters.

### ISSUE THREAD

**Issue by g12265080** [DavidePastore/Slim-Validation#24]
Currently it seems to be no optional parameters support. This could be useful in validation module.

For example;
```
$updateUserProfileValidators = array(
	'user_id' => $idValidator,
	'password' => $passwordValidator,
	'display_name' => $textValidator
);
```

In this case of updating user's profile, `password` and `display_name` parameters could be optional. Using `v::optional()` from Respect/Validation isn't suffice because there's no way to distinguish missing from null parameters in validation layer.

```
$updateUserProfileValidators = array(
	'user_id' => $idValidator,
	'password' => v::optional($passwordValidator),
	'display_name' => v::optional($textValidator)
);
```
Above code will allow `password=""` or `password=null` to pass validation process. This shifts burden to data processing layer in order to validate the password parameter again which would be redundant.
While missing parameter (password parameter not supplied at all) should pass, the blank or null password parameter shouldn't.

**Comment by DavidePastore** [comment]
Hi @g12265080 . Can you please include your validators definition? Maybe there is another way to do the same thing using Respect/Validation.
